
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
        {if $isEdit}
            action="{genUrl controller="patch-panel-port" action="edit" id=$object->getId()}"
        {else}
            action="{genUrl controller="patch-panel-port" action="add"}"
        {/if}>
            
<div class="row-fluid">

    <div class="span12">
    
        <fieldset>
            {$element->position}
            {$element->medium}
            {$element->connector}
            {$element->available_for_use}
            {$element->duplex}
            {$element->colo_reference}
            {$element->assigned}
            {$element->connected}
            {$element->cancelled}
            {$element->notes}
        </fieldset>
        
    </div>

</div>
        
    
</div>


<div class="form-actions">

    {$element->cancel}
    {$element->submit}

</div>

    
</form>


<script type="text/javascript">

$(document).ready( function(){
	
    $('#datejoin').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });
    
    $('#dateleave').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });

    if( $('#datejoin').val().length > 10 )
        $('#datejoin').val( $('#datejoin').val().substr( 0, 10 ) );

    if( $('#dateleave').val().length > 10 )
        $('#dateleave').val( $('#dateleave').val().substr( 0, 10 ) );

    $( '#type' ).bind( 'change', function( event ){
        if( $( '#type' ).val() == 2 )  // associate member
        {
            $( '#full-member-details' ).slideUp( 'fast' );
            $( '#full-member-details2' ).slideUp( 'fast' );
        }
        else {
            $( '#full-member-details2' ).slideDown( 'fast' );
            $( '#full-member-details' ).slideDown( 'fast', function() {
                //$( '#irrdb' ).trigger( "liszt:updated" );
                //$(".chzn-select").chosen();
            });
        }
    });

    $( "#name" ).on( "change", function(){
        if( $( '#abbreviatedName' ).val() == "" )
            $( '#abbreviatedName' ).val( $('#name' ).val() );
    });

    {if $isEdit and $object->getType() eq 2}
        $( '#full-member-details' ).slideUp( 'fast' );
        $( '#full-member-details2' ).slideUp( 'fast' );
    {/if}

    $( '#type' ).trigger( 'change' );
    
});

</script>

