<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PatchPanelPortObject
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchPanelPortObject extends EntityRepository
{
}
